### ISSUE TITLE
where is the test code?

### ISSUE THREAD

**Issue by Darknesszlx** [samet-akcay/ganomaly#14]
After training, how could we test a single image to classify whether it's fake or real without using test() in  model.py?

**Comment by samet-akcay** [comment]
You could write a similar function to test() in which you could forward-pass a single image into the model instead of passing the entire test set.

**Comment by lanlanwei** [comment]
> You could write a similar function to test() in which you could forward-pass a single image into the model instead of passing the entire test set.
Thank you for your amazing work.I have a question about the test().
You meat that a test() funcation like train.py，do you?
I really want to know.
Thank you very much.

**Comment by lanlanwei** [comment]
> After training, how could we test a single image to classify whether it's fake or real without using test() in model.py?

Hello.I have a problem the same as you,do you solve the problem?
I hope can ｄｉｓｃｕｓｓ with you,thank you very much.

**Comment by SriPradi** [comment]
@lanlanwei did you find the way to test images from custom dataset. Thanks

**Comment by lzzlxxlsz** [comment]
> > After training, how could we test a single image to classify whether it's fake or real without using test() in model.py?
> 
> Hello.I have a problem the same as you,do you solve the problem?
> I hope can ｄｉｓｃｕｓｓ with you,thank you very much.

你好，请问在你的数据集上效果怎么样呢
