### ISSUE TITLE
There are some mistakes in GANomaly paper

### ISSUE THREAD

**Issue by lujunsincerely** [samet-akcay/ganomaly#17]
In paper 3.2 Model Training, the Encoder Loss  part :
1)In last sentence which is write "'Lcon is formally defined as Lenc=...."  ,It's a mistake i think,the 'Lcon' should be corrected to  'Lenc'.
2) In second sentence "encoder loss Lcon to minimize the..."  should  corrected  'Lcon' to Lenc  too.

**Comment by samet-akcay** [comment]
Thank you for spotting this. I'll be updating this in the final version of the paper.
