### ISSUE TITLE
How can I entered mnist data to ./data folder ?

### ISSUE THREAD

**Issue by bemoregt** [samet-akcay/ganomaly#2]
Hi, @samet-akcay 

How can I entered mnist data to ./data folder ?

It needs ubyte type? or npz type?

from @bemoregt.

**Comment by samet-akcay** [comment]
Hi @bemoregt, 

You don't need to do anything. When you just train the model on MNIST data, the script first checks whether you have MNIST data within the directory. If it is not there, it downloads it automatically and creates an anomaly dataset from it.

For instance, when you run `sh experiments/run_mnist.sh`, the dataset will be downloaded if it is not in the directory.

**Comment by bemoregt** [comment]
Hi, @samet-akcay 

Thanks quick reply.

But I met this error when run your code.

-------------- End ----------------
Traceback (most recent call last):
  File "train.py", line 46, in <module>
    main()
  File "train.py", line 35, in main
    dataloader = load_data(opt)
  File "/home/kerb/ganomaly/lib/data.py", line 73, in load_data
    opt.anomaly_class = int(opt.anomaly_class)
ValueError: invalid literal for int() with base 10: '{0..9}'

----------------------------------------------------------------------

What's wrong with me?

from @bemoregt.

**Comment by samet-akcay** [comment]
Can you please paste here the command you run in terminal?

**Comment by bemoregt** [comment]
Hi, @samet-akcay 

This matter is fixed when I using Pytorch 0.3.

But Another Problems happen.

That matter is on another issue. 

from @bemoregt.
