### ISSUE TITLE
What are dimensionalities of images in UBD and FFOB catasets?

### ISSUE THREAD

**Issue by Ishitori** [samet-akcay/ganomaly#29]
I see that many people ask you to release datasets, but, unfortunately you cannot do that. That's fine.

I want to ask you how big the images are? Are we talking about 500x500 pixels? Or even 1024x1024? I haven't found this information in the paper.

Thank you.

**Comment by trondhain** [comment]
I think the size of these images is 256 x 256.
According to https://github.com/samet-akcay/ganomaly/blob/master/train.py#L9

**Comment by Ishitori** [comment]
Yes, I saw this code, but then I thought that x-ray scans of the luggage should be way bigger than that. But it is ok.
