### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by JiweiTian** [samet-akcay/ganomaly#30]
Hi, there are something wrong when i try to run your codes:
  File "E:/software/installation/Anaconda3/envs/CleverHans_py3.5/Lib/site-packages/ganomaly/train.py", line 35, in <module>
    dataloader = load_data(opt)
  File "E:\software\installation\Anaconda3\envs\CleverHans_py3.5\Lib\site-packages\ganomaly\lib\data.py", line 99, in load_data
    abn_cls_idx=opt.anomaly_class
AttributeError: can't set attribute

I don't know the ture reason, can you help me?
Thank you.

**Comment by ravishankarkannan** [comment]
I'm having the same issue, Any help is appreciated. 
Thanks
Stacktrace: 
`
Taceback (most recent call last):
  File "train.py", line 35, in <module>
    dataloader = load_data(opt)
  File "../ganomaly/lib/data.py", line 101, in load_data
    abn_cls_idx=opt.anomaly_class
AttributeError: can't set attribute`

**Comment by ymmshi** [comment]
I have solved this problem,  just downgrade the version of `torchvison`, umm, or edit the `requirements.txt` as 
```
torch==0.4.0
torchvision==0.2.1
tqdm==4.23.4
visdom==0.1.8.3
```

**Comment by JiweiTian** [comment]
I'm having the following issue, Any help is appreciated.
http.client.UnknownProtocol: HTTP/2.0

**Comment by lzzlxxlsz** [comment]
hello，have you run the code successfully?

**Comment by samet-akcay** [comment]
Hi, the repo has been updated. Can you check if you still encounter the same issues?

**Comment by samet-akcay** [comment]
I'm closing this issue since the latest commit should resolve this. Please reopen if you still encounter the same issue with the latest stable version.
