### ISSUE TITLE
Visualization on Custom Dataset

### ISSUE THREAD

**Issue by zhaobingbingbing** [samet-akcay/ganomaly#32]
Hi,
Thanks for your work, I have a question about when I train on mnist or cifar10 dataset, in the file of "output", there will be the visualization result， but when I train on my own dataset, there won't be any visualization result. Should I set for simething?
Thanks again for your kind reply.

**Comment by lzzlxxlsz** [comment]
你好，你运行完这个程序了吗，进行测试了吗

**Comment by DannisZgggg** [comment]
you can check whether you have set --outf
`self.parser.add_argument('--outf', default='./output', help='folder to output images and model checkpoints')`

**Comment by samet-akcay** [comment]
Due to inactivity, I assume this has been resolved, and am closing this issue. Please reopen if you still encounter the same issue with the latest version.
