### ISSUE TITLE
ImportError: No module named lib.data

### ISSUE THREAD

**Issue by bemoregt** [samet-akcay/ganomaly#4]
Hi, @samet-akcay 

At this time, I met this error.

  File "train.py", line 22, in <module>
    from lib.data import load_data
ImportError: No module named lib.data
----------------------------------------
What's wrong with me?

Thanks, at any rate.

from, @bemoregt.

**Comment by samet-akcay** [comment]
This is peculiar. If you correctly download or cloned the repository, then the file should be there. If you browse to lib folder, you'll see data.py, inside of which there is load_data function.

**Comment by samet-akcay** [comment]
Due to the inactivity, I assume this has been resolved, and am closing the issue.

**Comment by huguespoiget** [comment]
I guess the problem is that you didn't create an empty file __init__.py in lib directory, then it fails when executing `sh experiments/run_mnist.sh`

See below:

```
hugues@duncan:~/ganomaly$ sh experiments/run_mnist.sh
Manual Seed: {0..2}
Running mnist_{0..9}
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from lib.data import load_data
ImportError: No module named lib.data
hugues@duncan:~/ganomaly$ ls lib/
data.py  evaluate.py  loss.py  model.py  networks.py  visualizer.py
hugues@duncan:~/ganomaly$ touch lib/__init__.py
hugues@duncan:~/ganomaly$ sh experiments/run_mnist.sh
Manual Seed: {0..2}
Running mnist_{0..9}
usage: train.py [-h] [--dataset DATASET] [--dataroot DATAROOT]
                [--batchsize BATCHSIZE] [--workers WORKERS] [--droplast]
                [--isize ISIZE] [--nc NC] [--nz NZ] [--ngf NGF] [--ndf NDF]
                [--extralayers EXTRALAYERS] [--gpu_ids GPU_IDS] [--ngpu NGPU]
                [--name NAME] [--model MODEL]
                [--display_server DISPLAY_SERVER]
                [--display_port DISPLAY_PORT] [--display_id DISPLAY_ID]
                [--display] [--outf OUTF] [--manualseed MANUALSEED]
                [--anomaly_class ANOMALY_CLASS] [--proportion PROPORTION]
                [--metric METRIC] [--print_freq PRINT_FREQ]
                [--save_image_freq SAVE_IMAGE_FREQ] [--save_test_images]
                [--load_weights] [--resume RESUME] [--phase PHASE]
                [--iter ITER] [--niter NITER] [--beta1 BETA1] [--lr LR]
                [--w_bce W_BCE] [--w_rec W_REC] [--w_enc W_ENC]
train.py: error: argument --manualseed: invalid int value: '{0..2}'
```

**Comment by samet-akcay** [comment]
The problem is the Python version. If you run the code on Python 2, this problem occurs. On Python 3, on the other hand, it runs flawlessly.

**Comment by fishman2008** [comment]
> The problem is the Python version. If you run the code on Python 2, this problem occurs. On Python 3, on the other hand, it runs flawlessly.

So how this could be resolved if using python 2.*?

**Comment by samet-akcay** [comment]
I've modified the respective part of the code. Now it works with Python2 as well.
