### ISSUE TITLE
can you upload the code of skip ganomaly

### ISSUE THREAD

**Issue by JiangAndy** [samet-akcay/ganomaly#40]
I have read your paper  of skip ganomaly, your results are so good. Can you release you code so that I can learn from that? Besides, your paper use the different loss compared with the loss in ganomaly.

**Comment by samet-akcay** [comment]
Hi, here is the [skip-ganomaly](https://github.com/samet-akcay/skip-ganomaly) repo.

**Comment by JiangAndy** [comment]
> Hi, here is the [skip-ganomaly](https://github.com/samet-akcay/skip-ganomaly) repo.

thanks a lot , I will learn form that.
