### ISSUE TITLE
'CIFAR10' object has no attribute 'train_data'

### ISSUE THREAD

**Issue by Andrew05200** [samet-akcay/ganomaly#41]
when I run bash experiments/run_cifar.sh in linux,the error are as follows:
 
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    dataloader = load_data(opt)
  File "/home/z00377882/wangpengxiang/ganomaly/lib/data.py", line 60, in load_data
    trn_img=dataset['train'].train_data,
AttributeError: 'CIFAR10' object has no attribute 'train_data'

**Comment by GerardMaggiolino** [comment]
This was fixed in the PR I've made - check #42 and it's corresponding PR.
