### ISSUE TITLE
Can't run successfully in my cpu only computer

### ISSUE THREAD

**Issue by Minqi824** [samet-akcay/ganomaly#62]
I have followed the steps in this project but I got the following errors:
![image](https://user-images.githubusercontent.com/39890732/75109690-a7c86a00-5660-11ea-91ad-4f75767c7145.png)

I tried to fix this problem by searching the answers in https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/67 and https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/360, but the error still exists.

So I really hope that someone could help me to figure it out. **My computer is Windows 10 and only has CPU.**

**Comment by RForestLiu** [comment]
you can try  the following code so that unset gpu.
`python train.py --dataset mnist --isize 32 --nc 1 --niter 15 --abnormal_class 9 --device cpu`

**Comment by Minqi824** [comment]
> you can try the following code so that unset gpu.
> `python train.py --dataset mnist --isize 32 --nc 1 --niter 15 --abnormal_class 9 --device cpu`

This code actually works for me. Thanks a lot !!!
