### ISSUE TITLE
How to distinguish a mnist_pic is normal or anomaly?

### ISSUE THREAD

**Issue by captainfffsama** [samet-akcay/ganomaly#75]
I have train a model on mnist,here is my opt config:
```python
Namespace(abnormal_class=0, batchsize=64, beta1=0.5, dataroot='', dataset='mnist', device='gpu', display=True, display_id=0, display_port=8097, display_server='http://localhost', droplast=True, extralayers=0, gpu_ids=[0], isTrain=True, isize=32, iter=0, load_weights=False, lr=0.0002, manualseed=-1, metric='roc', model='ganomaly', name='ganomaly/mnist', nc=1, ndf=64, ngf=64, ngpu=1, niter=15, nz=100, outf='./output', phase='train', print_freq=100, proportion=0.1, resume='', save_image_freq=100, save_test_images=True, w_adv=1, w_con=50, w_enc=1, workers=8)
```

then I wanna use this model distinguish a mnist pic is normal or anomaly...
according paper anomaly score is count by:
![](https://raw.githubusercontent.com/hqabcxyxz/MarkDownPics/master/image/ganomaly_score.png)

so I write a inference py to count one mnist pic score like this:
```python
                fake,latent_i,latent_o=self.netg(data)
                error = torch.mean(torch.abs(latent_i-latent_o), dim=1)
                print(error.detach().item())
```

but I notice that it hard find a thresold from error to dsitinguish anormaly. `0`is set be anomaly class,but model still have a good capacity to reconstruct.
there anyone can tell me how to distinguish anomaly ?

**Comment by captainfffsama** [comment]
I notice that if I just ust 1 as normal class and make 0 as abnormal class, Generater can not reconstruct easily...
When I use 1,2,3,4,5 as normal class , generater can reconstruct 0 easily and it become hard to distinguish abnormal and nomal...

**Comment by GraceKafuu** [comment]
Hi, hqabcxyxz! Can you share your inference py?

**Comment by captainfffsama** [comment]
> Hi, hqabcxyxz! Can you share your inference py?

just use the test function in orignal work....

```python
import os
from math import ceil
from concurrent import futures

import torch
from torchvision.transforms import transforms
from PIL import Image
from tqdm import tqdm

from lib.networks import NetG,NetD
from lib.data import load_data
from options import Options

class Ganomaly_i(object):
    @property
    def name(self): return 'Ganomaly'

    def __init__(self,opt,dataset=None):
        self.opt=opt
        self.device = torch.device("cuda:0" if self.opt.device != 'cpu' else "cpu")
        self.netg=NetG(self.opt).to(self.device)
        self.init_netg()
        self.infer_trans=self.init_trans(dataset)
        self.dataset=dataset
        print('g init done!')

    def init_trans(self,dataset):
        transform=None
        if 'mnist'==dataset:
            transform = transforms.Compose(
                    [
                        transforms.Resize(self.opt.isize),
                        transforms.ToTensor(),
                        transforms.Normalize((0.1307,), (0.3081,))
                    ]
                )
        return transform

    def init_netg(self,path=None):
        if path is None:
            path = "./output/{}/{}/train/weights/netG.pth".format(self.name.lower(), self.opt.dataset)
            pretrained_dict = torch.load(path)['state_dict']

            try:
                self.netg.load_state_dict(pretrained_dict)
            except IOError:
                raise IOError("netG weights not found")
            print('   Loaded weights.')
        self.netg.eval()

    def inference(self,imgs_path,dataset='mnist'):
        result_total=[]
        if self.dataset !=dataset:
            self.infer_trans=self.init_trans(dataset)
        for data_batch in tqdm(self._deal_imgs(imgs_path)):
            error=self.forward(data_batch)
            result_total.append(error.squeeze_())
        return torch.cat(result_total,dim=-1)

    def inference_dataloader(self,dataloader):
        result=[]
        for data in dataloader['train']:
            error=self.forward(data[0].to(self.device))
            result.append(error.squeeze_())
        return torch.cat(result,dim=-1)

    def forward(self,data):
        with torch.no_grad():
            fake,latent_i,latent_o=self.netg(data)
            error = torch.mean(torch.abs(latent_i-latent_o), dim=1)

        return error.detach().cpu()

    def _read_batch_imgs(self,imgs_path,max_batch):
        data_list=[]
        with futures.ThreadPoolExecutor(max_batch) as exec:
            tasks=exec.map(self._read_img,imgs_path)
            for task in tasks:
                data_list.append(task)
        return torch.stack(data_list,dim=0)

    def _read_img(self,img_path):
        data=Image.open(img_path)
        return self.infer_trans(data)

    def _deal_imgs(self,imgs_path,max_batch=16):
        group_num=ceil(len(imgs_path)/max_batch)
        for i in range(group_num):
            data_batch=self._read_batch_imgs(imgs_path[i*max_batch:min((i+1)*max_batch,len(imgs_path))],max_batch)
            yield data_batch.to(self.device)

def get_imgs_path(img_dir:str):
    imgs_path=[]
    if img_dir.endswith('.txt'):
        with open(img_dir,'r') as fr:
            imgs_path=[path.strip() for path in fr.readlines()]
    if os.path.isdir(img_dir):
        for root,_,filenames in os.walk(img_dir):
            for filename in filenames:
                if '.bmp'==os.path.splitext(filename)[-1]:
                    imgs_path.append(os.path.join(root,filename))

    return imgs_path

def main(img_path:str):
    opt=Options().parse()
    print(opt)
    img_path_list=get_imgs_path(img_path)
    model=Ganomaly_i(opt)
    dataloader=load_data(opt)
    # result=model.inference_dataloader(dataloader)
    result=model.inference(img_path_list)

if __name__=='__main__':
    img_path='/home/chiebotgpuhq/MyCode/dataset/t10k-images/0'
    main(img_path)
```

**Comment by jiaji-fang** [comment]
> > Hi, hqabcxyxz! Can you share your inference py?
> 
> just use the test function in orignal work....
> 
> ```python
> import os
> from math import ceil
> from concurrent import futures
> 
> import torch
> from torchvision.transforms import transforms
> from PIL import Image
> from tqdm import tqdm
> 
> from lib.networks import NetG,NetD
> from lib.data import load_data
> from options import Options
> 
> class Ganomaly_i(object):
>     @property
>     def name(self): return 'Ganomaly'
> 
>     def __init__(self,opt,dataset=None):
>         self.opt=opt
>         self.device = torch.device("cuda:0" if self.opt.device != 'cpu' else "cpu")
>         self.netg=NetG(self.opt).to(self.device)
>         self.init_netg()
>         self.infer_trans=self.init_trans(dataset)
>         self.dataset=dataset
>         print('g init done!')
> 
>     def init_trans(self,dataset):
>         transform=None
>         if 'mnist'==dataset:
>             transform = transforms.Compose(
>                     [
>                         transforms.Resize(self.opt.isize),
>                         transforms.ToTensor(),
>                         transforms.Normalize((0.1307,), (0.3081,))
>                     ]
>                 )
>         return transform
> 
>     def init_netg(self,path=None):
>         if path is None:
>             path = "./output/{}/{}/train/weights/netG.pth".format(self.name.lower(), self.opt.dataset)
>             pretrained_dict = torch.load(path)['state_dict']
> 
>             try:
>                 self.netg.load_state_dict(pretrained_dict)
>             except IOError:
>                 raise IOError("netG weights not found")
>             print('   Loaded weights.')
>         self.netg.eval()
> 
>     def inference(self,imgs_path,dataset='mnist'):
>         result_total=[]
>         if self.dataset !=dataset:
>             self.infer_trans=self.init_trans(dataset)
>         for data_batch in tqdm(self._deal_imgs(imgs_path)):
>             error=self.forward(data_batch)
>             result_total.append(error.squeeze_())
>         return torch.cat(result_total,dim=-1)
> 
>     def inference_dataloader(self,dataloader):
>         result=[]
>         for data in dataloader['train']:
>             error=self.forward(data[0].to(self.device))
>             result.append(error.squeeze_())
>         return torch.cat(result,dim=-1)
> 
>     def forward(self,data):
>         with torch.no_grad():
>             fake,latent_i,latent_o=self.netg(data)
>             error = torch.mean(torch.abs(latent_i-latent_o), dim=1)
> 
>         return error.detach().cpu()
> 
>     def _read_batch_imgs(self,imgs_path,max_batch):
>         data_list=[]
>         with futures.ThreadPoolExecutor(max_batch) as exec:
>             tasks=exec.map(self._read_img,imgs_path)
>             for task in tasks:
>                 data_list.append(task)
>         return torch.stack(data_list,dim=0)
> 
>     def _read_img(self,img_path):
>         data=Image.open(img_path)
>         return self.infer_trans(data)
> 
>     def _deal_imgs(self,imgs_path,max_batch=16):
>         group_num=ceil(len(imgs_path)/max_batch)
>         for i in range(group_num):
>             data_batch=self._read_batch_imgs(imgs_path[i*max_batch:min((i+1)*max_batch,len(imgs_path))],max_batch)
>             yield data_batch.to(self.device)
> 
> def get_imgs_path(img_dir:str):
>     imgs_path=[]
>     if img_dir.endswith('.txt'):
>         with open(img_dir,'r') as fr:
>             imgs_path=[path.strip() for path in fr.readlines()]
>     if os.path.isdir(img_dir):
>         for root,_,filenames in os.walk(img_dir):
>             for filename in filenames:
>                 if '.bmp'==os.path.splitext(filename)[-1]:
>                     imgs_path.append(os.path.join(root,filename))
> 
>     return imgs_path
> 
> def main(img_path:str):
>     opt=Options().parse()
>     print(opt)
>     img_path_list=get_imgs_path(img_path)
>     model=Ganomaly_i(opt)
>     dataloader=load_data(opt)
>     # result=model.inference_dataloader(dataloader)
>     result=model.inference(img_path_list)
> 
> if __name__=='__main__':
>     img_path='/home/chiebotgpuhq/MyCode/dataset/t10k-images/0'
>     main(img_path)
> ```

Do you solve this issue? if you want to distinguish an images, why you load G-model when inference

**Comment by hsekki** [comment]
Hi , how to make inference for one image and output as normal or abnormal image.? Still cannot understand the use of this in classification task. Appreciate your response. Thanks.

**Comment by tobybreckon** [comment]
You need to threshold the anomaly score to give you the TP vs. FP characteristics you want.

Choose your threshold based on ROC or similar.

**Comment by hsekki** [comment]
@tobybreckon Thank you very much for your response. Where in the code can I set the threshold? Also, during inference, do we need the netD or just use the netG? I try changing the code to infer in one image but I got many values for the error in test function in model.py. How can I use this to classify normal vs. abnormal? Thanks again.

**Comment by tobybreckon** [comment]
Find the output  value that is the anomaly score for that image the version of the code _you_ have modified. Threshold that ...

**Comment by hsekki** [comment]
Here is the sample output of the test() function in model.py for one image. How can I know the anomaly score? Thank u.
print(latent_i.shape)
error = torch.mean(torch.pow((latent_i-latent_o), 2), dim=1)
print(error.detach().cpu())
print(self.input.size())
print(error.size())

torch.Size([1, 100, 22, 13])
tensor([[[2.1114, 1.7459, 1.7541, 1.4773, 1.8986, 2.0250, 1.9214, 2.0791,
          2.5610, 2.6672, 2.7503, 2.4636, 2.2367],
         [1.9690, 1.9735, 1.7926, 2.0642, 2.2656, 2.3004, 2.4851, 2.6950,
          2.9816, 3.2065, 3.2627, 2.5997, 2.2896],
         [1.9456, 1.8357, 2.0925, 1.8751, 2.3569, 2.4760, 2.3803, 2.5973,
          2.6974, 2.7088, 2.7212, 2.4553, 2.4625],
         [2.0791, 1.7848, 2.0896, 2.1127, 2.0547, 2.0192, 2.3366, 2.5419,
          2.2330, 2.5367, 2.4249, 2.5580, 2.6480],
         [2.1256, 2.0802, 2.0457, 2.6136, 2.3458, 2.3294, 2.3390, 2.6167,
          2.6066, 2.6431, 2.8858, 2.0254, 2.3441],
         [2.0384, 2.1815, 2.0674, 2.4062, 2.4199, 2.4403, 2.5503, 2.4981,
          2.2971, 2.3013, 2.4800, 2.5970, 1.9896],
         [2.0315, 2.0205, 2.4507, 2.1801, 2.3796, 2.4819, 2.4254, 2.3359,
          2.4044, 2.2716, 1.9355, 2.1884, 1.9788],
         [1.9710, 2.1006, 2.5248, 2.4712, 2.8490, 2.7702, 2.7956, 2.6212,
          2.2966, 2.4993, 2.2325, 2.2626, 2.4179],
         [2.0797, 1.9261, 2.2597, 2.4086, 2.6288, 2.6078, 2.3118, 2.5234,
          2.6862, 2.2393, 2.2667, 2.0814, 2.4036],
         [2.2775, 1.8365, 1.8261, 1.8883, 2.2579, 2.7680, 2.5955, 2.5562,
          2.3482, 2.2507, 1.9981, 2.0570, 2.0501],
         [2.3725, 1.9624, 1.8412, 1.9899, 2.1308, 2.3367, 2.7121, 2.5809,
          2.3881, 2.5543, 1.8620, 2.1990, 1.9885],
         [1.9783, 1.9454, 1.6192, 1.7504, 1.9908, 2.2058, 2.0696, 2.5223,
          2.0887, 1.8816, 1.6380, 2.1746, 1.5725],
         [2.0568, 2.0634, 1.8186, 1.8451, 2.0444, 2.1628, 2.2769, 2.4368,
          2.4201, 2.1740, 2.1856, 1.9343, 1.5173],
         [1.6453, 2.0063, 2.1549, 1.8427, 2.2591, 2.2572, 2.3017, 2.3339,
          2.6016, 2.2600, 1.8359, 1.9106, 1.9177],
         [1.5671, 1.6643, 1.8128, 2.0015, 2.2123, 2.1737, 2.2234, 2.6058,
          2.3269, 2.2445, 2.2773, 1.9892, 1.6707],
         [1.6883, 1.5633, 1.5932, 1.6492, 2.2426, 2.3781, 2.9115, 3.0442,
          2.6367, 2.7239, 3.0320, 2.1789, 1.7407],
         [1.4998, 1.4605, 1.6430, 1.7717, 2.4319, 2.6759, 3.1372, 3.0981,
          3.1534, 3.2665, 2.8910, 3.0060, 2.3198],
         [1.5837, 1.6133, 1.6961, 1.5889, 2.0053, 2.4707, 3.2214, 2.7429,
          3.0732, 3.4064, 3.3016, 3.3656, 2.7611],
         [1.5324, 1.7561, 2.0290, 2.0642, 2.8163, 2.8096, 3.4935, 3.0074,
          3.4278, 3.6118, 3.4695, 3.7738, 3.0299],
         [1.5729, 1.6707, 2.4448, 2.0472, 2.6817, 3.1731, 4.1754, 4.0146,
          3.8623, 3.8256, 3.5327, 3.7522, 3.0852],
         [1.6260, 1.5174, 2.2895, 2.5104, 3.0397, 3.5898, 4.0344, 4.7303,
          3.8162, 3.9191, 3.6521, 3.4140, 2.6680],
         [1.6239, 1.7108, 2.1211, 2.6240, 2.8996, 3.7090, 4.1181, 4.4267,
          4.6949, 4.4422, 4.2914, 3.2571, 2.4246]]])
torch.Size([1, 3, 206, 128])
torch.Size([1, 22, 13])
----
And there is an error in the next line:
 self.an_scores[i*self.opt.batchsize : i*self.opt.batchsize+error.size(0)] = error.reshape(error.size(0))
RuntimeError: shape '[22]' is invalid for input of size 286

**Comment by tobybreckon** [comment]
If  you look at the code and comments in test() within model.py it actuality returns the full auc data. 

The anomaly scores are in self.an_scores it appears.

**Comment by hsekki** [comment]
It's actually the values from error variable, and there is shape issue when storing in an_scores variable. Should i get a single value for one image to classify it as anomalous or not? thanks.

**Comment by tobybreckon** [comment]
You should get a reconstruction error as per the paper.

Single value or 3 values if not yet collapsed across all channels as after as I know.

**Comment by hsekki** [comment]
Thank you very much for your response. Do you know how to write the classifier (0 or 1) to infer on one image on code? Or does anyone knows here. It will be a great help. Thanks.

**Comment by tobybreckon** [comment]
This is the anomaly score as described in the paper so you just need to choose a threshold to map it to {normal, anomaly}.

Look at the distribution of scores you get for your test data. Choose the threshold based on that. Hope this helps.

**Comment by hsekki** [comment]
Is it valid to have anomaly scores greater than one since I don't use normalization below because it just returns (nan) for one image. How can I find the best threshold that will separate normal and abnormal. Thanks again.
            # Scale error vector between [0, 1]
            self.an_scores = (self.an_scores - torch.min(self.an_scores)) / (torch.max(self.an_scores) - torch.min(self.an_scores))

**Comment by tobybreckon** [comment]
If unnormalised - yes.

The nan are occurring because you have 1 Image in the set and hence min == max and hence the demoninater is thus 0.

Use the min and max values obtained from the training data set to fix this.

**Comment by hsekki** [comment]
@tobybreckon , thank you. this is very helpful. Also, is it possible to use the model to classify an object detected by detector as anomalous or not? Is there a demo or sample? Thank u.
