### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by newlei** [samet-akcay/ganomaly#8]
Can you provide the dataset(University Baggage Anomaly Dataset) in your paper?

**Comment by samet-akcay** [comment]
Due to the security reasons raised by our collaborators, we won't be able to release UBA dataset at the moment. However, we do plan to release it in the long-term.

**Comment by ma3252788** [comment]
> Due to the security reasons raised by our collaborators, we won't be able to release UBA dataset at the moment. However, we do plan to release it in the long-term.

Can you share the data set now? Sincerely hope that you can open the data set, thank you very much!
