### ISSUE TITLE
doubt about encoder loss

### ISSUE THREAD

**Issue by ybpaopao** [samet-akcay/ganomaly#9]
Hi~I have run your code and the result is good. I have also read your paper. I found that L1 loss is used in your paper to define encode loss, but actually you use L2 loss in your code to define encode loss. Am I right? In addition, you have defined l2_loss in "loss.py". But you did not define the backward function of this error. So, I wonder how "self.err_g_enc" can  backward in your code. These questions trouble me a lot. It will glad if you can resolve these doubts. Thanks and good luck!

**Comment by samet-akcay** [comment]
Hi,
Thanks for spotting this! Actually, that is a typo in the paper, which should have been L2 (copy paste issues :) ). However, the results are quite similar when we use L1 as well. You could check it out if you want.

Concerning the loss function, there is no need to do so. When we use the original L1 or L2 loss, we have the following error:

```
"nn criterions don't compute the gradient w.r.t. targets - please " \
AssertionError: nn criterions don't compute the gradient w.r.t. targets - please mark these tensors as not requiring gradients
```
The error is because the original L1 or L2 loss functions that come with PyTorch expects two variables, the first of which should be `set_grad=True`, while the latter of which should be  `set_grad=False`. In our case, however, we have two variables, both of which should be `set_grad=True`. When we use the function we created (l1_loss), the output of the function is a variable whose gradients are computed by default. You could read more about this from the following link: 

```
https://discuss.pytorch.org/t/how-to-calculate-l1-loss-between-two-variables/2204/4
```

**Comment by ybpaopao** [comment]
@samet-akcay Thanks for your reply and i'm now understand the loss used in the code. Yes, I found that L1 loss and L2 loss actually achieved similar results. In addition, I wonder if you have tried your method in anomaly detection in videos, such as the UCSD as you mentioned in your code. Does you code can directly read images as input or you have processed the video data before you run GAnomaly? Thanks!

**Comment by samet-akcay** [comment]
We haven't trained UCSD, but one chap opened another issue here #10, raising UCSD training. Most of the video anomaly detection papers use temporal information within the UCSD, which we cannot do via Ganomaly. However, we could still train it like we do for the UBA dataset in the paper. You could read more about this here [README.md](https://github.com/samet-akcay/ganomaly/blob/master/README.md#train-on-custom-dataset).

**Comment by ybpaopao** [comment]
@samet-akcay Hi, I wonder if there are any functional differences between your codes of torch0.3 and torch0.4. Are they just implemented with different version of pytorch?

**Comment by samet-akcay** [comment]
@ybpaopao , There is no functional difference. As you said, the only difference is the PyTorch version.

**Comment by ybpaopao** [comment]
@samet-akcay Hi, I  tried to implement the work in video anomaly detection. However, I meet some problems when I test the code in UCSD PED dataset according the guidance you provided in readme.txt. The err_d_real and err_d_fake are always 0 and 27.631 from the first iteration. I guess may be the DNet did not work very well. By the way, the adversarial loss you defined in your paper is the L2 loss between the DNet outputs of real sample and a fake generated sample. But I found in the code that "self.err_g_bce = self.bce_criterion(self.out_g, self.label)". It seems that you use the binary entropy-cross error between the true label and the DNet output of the fake generated sample. Does this matters? Or do you have any suggestions about the strange err_d_real and err_d_fake?

**Comment by samet-akcay** [comment]
Hi @ybpaopao, if the error gets stuck between 0 and 27.631, then it is highly likely that mode collapse occurs. How do you train UCSD? Are you working with full images, or sliding window patches?

For the adversarial loss, we tried both, and as we said in the paper, feature matching works better. Seems like we forgot to update the code, though. I’ll update the code accordingly.
