### ISSUE TITLE
Program stucks when the input image size is 224x224

### ISSUE THREAD

**Issue by e96031413** [samet-akcay/ganomaly#90]
Hello, when I use input size of 32, 64, 128, 256, the training works smoothly, however, when it comes to 224, the program stucks in load model phase.

How can I modify the architecture to prevent the problem?

Thanks in advance.

**Comment by tobybreckon** [comment]
Almost certainly as 224 is not a power of 2, and hence some down/up sampling dimensions that are auto-calculated/set relative to the input size breaks somewhere.

Solutions - zero pad (all sides of image) or resize to 256 ...then train.

**Comment by e96031413** [comment]
@tobybreckon Thanks for your explanation.
